package antonio.camas.shop;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


//(scanBasePackages={"antonio.camas.shop"})
@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}

//http://www.plantuml.com/plantuml/uml/hLJ1RXen4BtxA-ROIcsuLoKDAQYNg8cKSAxCUc0jl3QonmN-llOEgoNriZHjSuXOpvltFC_FlWiaFSN625cHyx0Cw4NbZC6AjBC1xhtR5skosg9LGacIAnaGvlT2JAVm8AtITWDFSeCmdGgHsU3ZRKS2ds2YhSB3JKr9aLSPm8m9y6tnyXh4bGHAAgc-GGBdLMepEf18Q-VjvwM-yxh-agllSYDpX0yWKxF5FN-_RoVydZuVysSUhvpkgz7L5fpjsqQ6J9WVBQOOj2SiGCMMryutqKX_7DWEMa8VW6e4qcHG2EFS3cpwQZ08WB9bfXGG7WZS6ZHXaq2bPgZTlgs2jY3PxI6oAjlHKbeyDQmYaRENMIL3xIuIxsEjqIYHqoOk2OHK7VRvwV4v6Lrvb8Hiut2e6D6VMdRE7z-OeAAQ0_DSkxF4Z4NcMbooFJp3vBDMjoCNOw-fXemfReT7YluanOZ14KS3nyCe9AbDw6uCXoNm9PcZGS9-wertSGThxngOzDGNZzFPLmm3Mv06FS7C8nnTX10zVXbWEs8OjdE-U5YyB62YMfKnJnbH-lNNaKYjhKNBdPB_Pb5c6B5ePanQ0bIQyejCDV89tVp-14X3K7aN0hX8tPNFVwLs8_ssHK1LOxLTkSC9MiWpIWTcHfMv4nPDmCxJKIMUCaCwEByRL_KOhJejgTIuqDWB1V3MLme0xPMtobbubZznE9ZBf_dipu8P-VJ_Rp3lqh-OVly2
